version: 2
jobs:
  build:
    docker:
      - image: docker:17.11.0-ce
    working_directory: ~/workspace
    environment:
      GIT_TERMINAL_PROMPT: 0
      DOCKER_OWNER: emojigen
      DOCKER_IMAGE: node-py23
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
          docker_layer_caching: true
      - checkout
      - run:
          name: Build
          command: docker build -t $DOCKER_OWNER/$DOCKER_IMAGE:latest .
      - run:
          name: Docker Login
          command: |
            if [ "$CIRCLE_BRANCH" == 'master' ]; then
              echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin
            fi
      - run:
          name: Debug
          command: |
            if [ "$CIRCLE_BRANCH" == 'master' ]; then
              apk add -U -q --no-progress ca-certificates git jq sed wget
              ./.circleci/setup-git.sh
              ./.circleci/update-dockerfile.sh
              ./.circleci/update-remote.sh
            fi
      - run:
          name: Push image to registory
          command: |
            if [ "$CIRCLE_BRANCH" == 'master' ]; then
              NODE_VERSION=$(fgrep 'node:' Dockerfile | sed -E 's/^.*node\:([0-9\.]+).*$/\1/')
              PYTHON2_VERSION=$(fgrep 'python:2' Dockerfile | sed -E 's/^.*python\:([0-9\.]+).*$/\1/')
              PYTHON3_VERSION=$(fgrep 'python:3' Dockerfile | sed -E 's/^.*python\:([0-9\.]+).*$/\1/')
              TAG_NAME="node$NODE_VERSION-py$PYTHON2_VERSION-py$PYTHON3_VERSION"

              docker tag $DOCKER_OWNER/$DOCKER_IMAGE:latest $DOCKER_OWNER/$DOCKER_IMAGE:$TAG_NAME
              docker push $DOCKER_OWNER/$DOCKER_IMAGE
              docker push $DOCKER_OWNER/$DOCKER_IMAGE:$TAG_NAME
            fi
